### ISSUE TITLE
Using any commands fails

### ISSUE THREAD

**Issue by noraj1337** [osteth/HBCTF#3]
I created a virtual env:

```
$ virtualenv  /tmp/MyEnv
$ source /tmp/MyEnv/bin/activate
$ pip install --upgrade setuptools pip wheel
```

I didn't understand what this means:

> Then install in locally editable (-e) mode and run the tests.
>
>```
> sudo pip install -e .[test]
> py.test
> ```

So I ran `# python3 setup.py install` instead.

And when using any commands:

```
(MyEnv) $ HBCTF initdb                                                                                                                                                                                 [±master ✓]
Traceback (most recent call last):
  File "/usr/bin/HBCTF", line 11, in <module>
    load_entry_point('HBCTF==0.0.1.dev0', 'console_scripts', 'HBCTF')()
  File "/home/noraj/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/noraj/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/noraj/.local/lib/python3.6/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/noraj/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/noraj/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'port'
```

It seems to request soem ressources out of the virtual env.

**Comment by osteth** [comment]
just tested it and everything that is currently built is working.  To get started you have to install the repo and its dependencies. I have utilized setuptools to handle this and make it very easy to do.  If you with to simply install the repo you just go into the directory and type
pip install
if you would like it to be editable so that you can make changes to the source and not have to reinstall after every change then you install is with the editable flag by going into the directory and typing.
pip install -e
to install it as well as installing the requirements for running unit test then you install it by going into the directory and typing in 
pip install -e.[test]
I hope this help. I only have limited experience so this is only my interpretation of how it works, I may be wrong. you may also have to run the commands as sudo because it attempts to install packages. 

I work in a conda container personally so I am not sure about how things work in a virtualenv. but it's my understanding that they are about the same. I am learning a lot as I program this so im not 100% about the fine details of how everything works but I believe everything that is programmed so far should be functional now. 
thank you for submitting the issue all help is greatly appreciated : )

**Comment by noraj** [comment]
```
$ pip install
You must give at least one requirement to install (see "pip help install")

$ pip install -e.[test]
zsh: no matches found: -e.[test]

$ pip install -e

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument
```

I think you meant `pip install .` but it's better to use `python setup.py install`.

**Comment by osteth** [comment]
I start my projects using pyskel https://github.com/mapbox/pyskel
you can use the sample project to troubleshoot if you like since it is lighter. 
I promise that it works for me and many others. I think you may not have moved into the source directory or something?

**Comment by noraj** [comment]
I used `python setup.py install` and it works but the installation steps was not clear about that. I can't make `pip install -e.[test]` works.
